name: Build and publish a Docker image to ghcr.io

on:
 push:
  secrets: # Required to install pipci from source
    GH_SSH_KEY:
      required: true

# Docker registry:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker_publish:
    runs-on: ubuntu-latest

    permissions: # Required to push docker image
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    # Login to container registry:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build image:
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      run: ./build_container.sh
      with:
        context: .
        load: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest 

    # Push image to registry:
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
    - name: Push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


